# SPDX-FileCopyrightText: 2026 RAprogramm <andrey.rozanov.vl@gmail.com>
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = ["Cargo.toml", "Cargo.lock"]
SPDX-FileCopyrightText = "2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["README.md", "CHANGELOG.md", "SECURITY.md"]
SPDX-FileCopyrightText = "2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/**", ".gitignore", ".gitattributes"]
SPDX-FileCopyrightText = "2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["benches/**", "examples/**", "tests/**"]
SPDX-FileCopyrightText = "2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/**"
SPDX-FileCopyrightText = "2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["*.json", "*.yml", "*.yaml", "*.toml"]
SPDX-FileCopyrightText = "2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/assets/**"]
SPDX-FileCopyrightText = "2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
