name: cargo check (no_std)

on:
  workflow_call:

jobs:
  check-no-std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-no-std
      - run: cargo check --no-default-features
