name: Test Results

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  test-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-nextest
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: test-results
          shared-key: stable
      - run: cargo nextest run --features "parallel,serde" --profile ci
        continue-on-error: true
      - if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          report-type: test_results
